### ISSUE TITLE
Virtual Classrooms

### ISSUE THREAD

**Issue by Eliaxie** [bebora/polimi-schedule-js#2]
hello, I think you already know what I'm about to describe, the script is no longer working because of the enhanced description of the Microsoft Teams virtual classrooms. You could delete them or, even more useful, add the virtual classroom in the event notes.

**Comment by bebora** [comment]
Thanks for the feedback, I didn't even notice because I was testing on the Manifesto degli Studi page. Unfortunately the second option is not applicable for the online converter as the Teams links are not available just by copying the text.
For istance, with one of my courses I would get something as
```
095898 - COMPUTING INFRASTRUCTURES  (Docente: Roveri Manuel )
Semestre: 2 Inizio lezioni: 24/02/2020 Fine lezioni: 26/05/2020

    Lunedì dalle 14:15 alle 16:15, lezione in aula SALA CONF. EMILIO GATTI (Milano Città Studi - Via Bassini - Edificio 20 - Piano Terra)
    Martedì dalle 08:15 alle 10:15, lezione in aula 26.11 (EX L.26.11) (Milano Città Studi - Via Golgi 20 - Edificio 26 - Piano Primo)

Aula virtuale per didattica a distanza
```
However I could work to integrate the links through the userscript, since it has access to the page DOM. This may be a little complex because I should either create a new parser for HTML and mantain it along the existing one or find a workaround to add links to created events created. Another problem is that I can only test this with my courses and I can't see if anything strange happens with annual courses, for example.
I'm going to remove the links for now, but I may add them to the Userscript later.
