### ISSUE TITLE
Virtual Classrooms

### ISSUE THREAD

**Issue by Eliaxie** [bebora/polimi-schedule-js#5]
Hello, we talked about this already but this time is easier.
I'm proposing to add either the webex classroom link or the teacher's name to the calendar, something like this (before and after)
![poliwebex1](https://user-images.githubusercontent.com/27226791/108823563-e456da80-75c0-11eb-9865-0c09440c7346.png)
![poliwebex2](https://user-images.githubusercontent.com/27226791/108823579-e9b42500-75c0-11eb-8fcc-695b791c7684.PNG)
This time there is no need to catch the hyperlink since webex room's names are all generated the same way https://politecnicomilano.webex.com/meet/ + name + surname, which you can get from "Docente: Surname Name"

**Comment by bebora** [comment]
This idea is interesting, however there are some problems:
1) Some professors share the same name and the tool can't guess the right one (e.g. paolo.giacomazzi and paolo1.giacomazzi both exist)
2) The rule to obtain the link from more complex names doesn't look to be "deterministic":
**MARANGONI MARCO** ANDREA is marco.marangoni
**MARTINEZ** VAZQUEZ **REBECA** is rebeca.martinez
**DELLA VALLE GIUSEPPE** is giuseppe.dellavalle
**GUEDON GAEL RAYMOND** is gaelraymond.guedon
How can we know what should and what shouldn't be on the link?
3) Some courses are as follows:
```
051124 - FISICA
Inizio lezioni: 22/02/2021  Fine lezioni: 04/06/2021

    Lunedì dalle 08:15 alle 10:15, lezione in aula AULA VIRTUALE LEO (-)
    Lunedì dalle 15:15 alle 17:15, esercitazione in aula 21.0.3 (EX E.G.6) (Milano Città Studi - Via Bassini - Edificio 21 - Piano Terra)
    Martedì dalle 11:15 alle 13:15, lezione in aula AULA VIRTUALE LEO (-)
    Mercoledì dalle 17:15 alle 19:15, esercitazione in aula 3.1.2 (EX S.1.2) (Milano Città Studi - Piazza Leonardo da Vinci 32 - Edificio 3 - Piano Primo)
    Mercoledì dalle 17:15 alle 19:15, esercitazione in aula 25.S.2 (EX D.0.3) (Milano Città Studi - Via Golgi 40 - Edificio 25 - Piano Seminterrato)
    Giovedì dalle 15:15 alle 17:15, esercitazione in aula 2.1.5 (EX N.1.5) (Milano Città Studi - Piazza Leonardo da Vinci 32 - Edificio 2 - Piano Primo)
    Venerdì dalle 10:15 alle 13:15, lezione in aula AULA VIRTUALE LEO (-)

    051193 - FISICA (MODULO 1) (Docente: D'Andrea Cosimo)
    Semestre: 2 Inizio lezioni: 22/02/2021 Fine lezioni: 04/06/2021
    Aula virtuale - D'Andrea Cosimo
    Aula virtuale - Ciappetta Giacinto
    Aula virtuale - Gatto Lorenzo
    Aula virtuale - Ciriolo Anna Gabriella

    051125 - FISICA (MODULO 2) (Docente: D'Andrea Cosimo)
    Semestre: 2 Inizio lezioni: 22/02/2021 Fine lezioni: 04/06/2021
    Aula virtuale - D'Andrea Cosimo
    Aula virtuale - Ciappetta Giacinto
    Aula virtuale - Gatto Lorenzo
    Aula virtuale - Ciriolo Anna Gabriella
```
The parser splits each course into subcourses (at least, now), and isn't able to find the professors name while looking at the dates here reported, but it is easily fixable. Would you use just the main professor name then?

The third one is minor, but the first two are more problematic, because they cause the output to be wrong. I can add a checkbox that enables a simple link guessing (i.e. [last/second word].[first word]) and explicitly tell the user that the links have a high chance to be wrong, but would it make sense at all to add such broken functionality?
What would you suggest?
Adding a possible wrong link or just adding the main professor name in the description of events?

**Comment by Eliaxie** [comment]
you raise valid concerns, the second seems fixable but the first one doesn't. What about just adding the name of the teacher(s) in the description? To me, this alone would be helpful for reminding me which virtual room I have to join without having to open polimi online services.

**Comment by bebora** [comment]
I'm thinking of an event description as follows:
```
[Lesson type] (Lesson/Training/Laboratory)
Professors: (Docenti if I detect Italian)
D'Andrea Cosimo
Ciappetta Giacinto
...
```
I'm already using the lesson type for a specific kind of schedule ([test example](../blob/master/scripts/test/input/architetturaSingoleDate2020Chromium.txt)), but I don't recall why I haven't added it for the regular schedule. I think it's doable but I'll look better later.

Would you approve something like this?
Or would you prefer only the main professor and/or no lesson type?

**Comment by Eliaxie** [comment]
Seems solid and very helpful, the version with the most amount of info would be better imo
